### PR TITLE
Update site to use latest theme

### PR DESCRIPTION
**Pull request by bdenham**
## Description

This PR updates the site to use the latest theme and Gatsby version. It also migrates the package manager from `npm` to `yarn`. These changes are in preparation for using the App Builder docs site to test search improvements.

## Related Issue

Search Enhancement and Local Search epics.

## Motivation and Context

Improve the search experience.

## How Has This Been Tested?

Local builds.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by timkim — COMMENTED** [review]
Does the deploy.yml need to be updated as well? I remember we were tinkering with some of the secrets in there.

**Comment by bdenham** [comment]
> Does the deploy.yml need to be updated as well? I remember we were tinkering with some of the secrets in there.

Good call. Updated and running tests now.

**Comment by timkim** [comment]
> > Does the deploy.yml need to be updated as well? I remember we were tinkering with some of the secrets in there.
> 
> Good call. Updated and running tests now.

Ya, I think it's these ones: https://github.com/AdobeDocs/dev-site-documentation-template/blob/main/.github/workflows/deploy.yml#L138

**Comment by bdenham** [comment]
@timkim: Yep, I'm updating all the workflows to reflect our new standard suite, minus the internal links tester which I will replace with a different action later.

**Review by timkim — APPROVED** [review]

**Pull request merged**
